language: ruby
rvm:
  - 2.1.2
script: "bundle exec rake spec:model"
notifications:
  email:
    recipients:
      - rinkusinghal05@gmail.com
    on_success: change
    on_failure: change
addons:
  code_climate:
    repo_token: dffd08ec4ad10ec28c1855bd2916c344ac411c4e312cf3862bee6dba64ea15fa